In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [8]:
df=pd.read_csv('/content/nasdaq100.csv',sep=';')

In [9]:
df.head()

       Date  Starting (USD)  Ending (USD)
0  01.01.24           16800         16500
1  01.12.23           15900         16100
2  01.11.23           15800         15300
3  01.10.23           16100         16200
4  01.09.23           16300         15700

In [10]:
df.shape

(12, 3)

In [12]:
df.drop(df[['Date']],axis=1,inplace=True)

In [13]:
df.head()

   Starting (USD)  Ending (USD)
0           16800         16500
1           15900         16100
2           15800         15300
3           16100         16200
4           16300         15700

In [14]:
df.shape

(12, 2)

In [15]:
df.columns

Index(['Starting (USD)', 'Ending (USD)'], dtype='object')

In [28]:
X=df[['Starting (USD)']]

In [29]:
X.head()

   Starting (USD)
0           16800
1           15900
2           15800
3           16100
4           16300

In [30]:
y=df[['Ending (USD)']]

In [31]:
y.head()

   Ending (USD)
0         16500
1         16100
2         15300
3         16200
4         15700

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [22]:
X_train.shape

(9,)

In [23]:
X.shape

(12,)

In [25]:
model=LinearRegression()

In [32]:
model=LinearRegression()
model.fit(X,y)

LinearRegression()

In [34]:
model.score(X,y)

0.3577804940272571

In [35]:
model.predict([[16800]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[16369.26885625]])