# Pandas Data Structures:
We have learned about **Series**, lets learn DataFrames (2<sup>nd</sup> workhorse of pandas) to expand our concepts of Series.

* DataFrame
* Grab data (column wise)
* Grab data (raw wise)
* Grabbing an element or a sub-set of the dataframe
* Adding new column
* Deleting the column
* boolean_mask
* boolean_mask(Combine 2 conditions)
* reset_index(), set_index(), head(), tail(), info(), describe()

## DataFrame
* A very simple way to think about the DataFrame is, "bunch of Series together such as they share the same index". <br>
* A DataFrams is a rectangular table of data that contains an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, etc). DataFrame has both a row and column index; it can be thought of as a dictionary of Series all sharing the same index. <br>

&#9758; *A good read for those, who are interested! ([Python for Data Analysis](http://shop.oreilly.com/product/0636920023784.do))<br>*

Let's learn **DataFrame with examples:**<br>

In [ ]:
import pandas as pd
import numpy as np

Let's create two labels/indexes:
* for rows 'r1 to r10'
* for columns 'c1 to c10'

Let's start with a simple example, using **`arange()`** and **`reshape()`** together to create a 2D array (matrix).<br>

In [ ]:
rows = ['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']
columns = ['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']

&#9989; *Use **TAB** for auto-complete and **shift + TAB**  for doc.*

In [ ]:
# How the index, columns and array_2d look like!
rows

['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']

In [ ]:
columns

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']

In [ ]:
array_2d = np.arange(0,100).reshape(10,10)

In [ ]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
df = pd.DataFrame(data = array_2d, index = rows, columns = columns)

In [ ]:
# How the DataFrame look like!
df # select * from df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
type(df)

pandas.core.frame.DataFrame

**df** is our first dataframe. <br>
We have columns, c1 to c10, and their corresponding rows, r1 to r10. <br>
Each column is actually a pandas series, sharing a common index (row labels). <br>

&#9758; Let's learn how to **Grab data** that we need, this is the most important thing we want to learn to move one!<br>

### Columns

In [ ]:
df[['c1', 'c7']] #select c1, c2 from df
#df.c10

     c1  c7
r1    0   6
r2   10  16
r3   20  26
r4   30  36
r5   40  46
r6   50  56
r7   60  66
r8   70  76
r9   80  86
r10  90  96

In [ ]:
# Grabbing a single column
df[['c5']]

     c5
r1    4
r2   14
r3   24
r4   34
r5   44
r6   54
r7   64
r8   74
r9   84
r10  94

In [ ]:
type(df[['c5']])

pandas.core.frame.DataFrame

In [ ]:
# Grabbing more than one column, pass the list of columns you need!
df[['c1', 'c10', 'c3']] #select c1, c10 from df

     c1  c10  c3
r1    0    9   2
r2   10   19  12
r3   20   29  22
r4   30   39  32
r5   40   49  42
r6   50   59  52
r7   60   69  62
r8   70   79  72
r9   80   89  82
r10  90   99  92

In [ ]:
df['c5']   # It is a pandas Series (single [])

r1      4
r2     14
r3     24
r4     34
r5     44
r6     54
r7     64
r8     74
r9     84
r10    94
Name: c5, dtype: int32

In [ ]:
type(df['c5'])

pandas.core.series.Series

**df.column_name (e.g. df.c1, df.c2 etc)** can be used to grab a column as well, its good to know but I don't recommend. <br>
If you press "TAB" after df., you will see lots of available methods, its good not to get confused with these option by using df.column_name.<br>
**Let's try this once**

### Adding new column
Lets try with "+" operation!

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
df['new']= df['c1'] + df['c2']  # select *, (c1 + c2) as new from df

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  new
r1    0   1   2   3   4   5   6   7   8    9    1
r2   10  11  12  13  14  15  16  17  18   19   21
r3   20  21  22  23  24  25  26  27  28   29   41
r4   30  31  32  33  34  35  36  37  38   39   61
r5   40  41  42  43  44  45  46  47  48   49   81
r6   50  51  52  53  54  55  56  57  58   59  101
r7   60  61  62  63  64  65  66  67  68   69  121
r8   70  71  72  73  74  75  76  77  78   79  141
r9   80  81  82  83  84  85  86  87  88   89  161
r10  90  91  92  93  94  95  96  97  98   99  181

In [ ]:
df['new2'] = 'A'

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  new new2
r1    0   1   2   3   4   5   6   7   8    9    1    A
r2   10  11  12  13  14  15  16  17  18   19   21    A
r3   20  21  22  23  24  25  26  27  28   29   41    A
r4   30  31  32  33  34  35  36  37  38   39   61    A
r5   40  41  42  43  44  45  46  47  48   49   81    A
r6   50  51  52  53  54  55  56  57  58   59  101    A
r7   60  61  62  63  64  65  66  67  68   69  121    A
r8   70  71  72  73  74  75  76  77  78   79  141    A
r9   80  81  82  83  84  85  86  87  88   89  161    A
r10  90  91  92  93  94  95  96  97  98   99  181    A

In [ ]:
df['new3'] = [4,7,10,13,16,19,22,25,28,31]

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  new new2  new3
r1    0   1   2   3   4   5   6   7   8    9    1    A     4
r2   10  11  12  13  14  15  16  17  18   19   21    A     7
r3   20  21  22  23  24  25  26  27  28   29   41    A    10
r4   30  31  32  33  34  35  36  37  38   39   61    A    13
r5   40  41  42  43  44  45  46  47  48   49   81    A    16
r6   50  51  52  53  54  55  56  57  58   59  101    A    19
r7   60  61  62  63  64  65  66  67  68   69  121    A    22
r8   70  71  72  73  74  75  76  77  78   79  141    A    25
r9   80  81  82  83  84  85  86  87  88   89  161    A    28
r10  90  91  92  93  94  95  96  97  98   99  181    A    31

### Deleting the column -- `drop()`

        *df.drop('new')-- ValueError: labels ['new'] not contained in axis

Shift+tab, you see the default axis is 0, which refers to the index (row labels), for column, we need to specify axis = 1.<br>
&#9758; rows refer to 0 axis and columns refers to 1 axis<br>
&#9758; Quick Check: *df.shape gives tuple (rows, cols) at [0] and [1]*

In [ ]:
# We can delete a column using drop()
# df.drop('new')# ValueError: labels ['new'] not contained in axis
df.drop('new', axis=1)      # axis=0 means row, axis=1 means column

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10 new2  new3
r1    0   1   2   3   4   5   6   7   8    9    A     4
r2   10  11  12  13  14  15  16  17  18   19    A     7
r3   20  21  22  23  24  25  26  27  28   29    A    10
r4   30  31  32  33  34  35  36  37  38   39    A    13
r5   40  41  42  43  44  45  46  47  48   49    A    16
r6   50  51  52  53  54  55  56  57  58   59    A    19
r7   60  61  62  63  64  65  66  67  68   69    A    22
r8   70  71  72  73  74  75  76  77  78   79    A    25
r9   80  81  82  83  84  85  86  87  88   89    A    28
r10  90  91  92  93  94  95  96  97  98   99    A    31

&#9758; Is the "new" really deleted? <br>
Output df and you will see "new" is still there!<br>

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  new new2  new3
r1    0   1   2   3   4   5   6   7   8    9    1    A     4
r2   10  11  12  13  14  15  16  17  18   19   21    A     7
r3   20  21  22  23  24  25  26  27  28   29   41    A    10
r4   30  31  32  33  34  35  36  37  38   39   61    A    13
r5   40  41  42  43  44  45  46  47  48   49   81    A    16
r6   50  51  52  53  54  55  56  57  58   59  101    A    19
r7   60  61  62  63  64  65  66  67  68   69  121    A    22
r8   70  71  72  73  74  75  76  77  78   79  141    A    25
r9   80  81  82  83  84  85  86  87  88   89  161    A    28
r10  90  91  92  93  94  95  96  97  98   99  181    A    31

To parmanently delete the column, you have to tell the pandas by setting<br>
* ***inplace = True*** (default is inplace=False).<br>

&#9989; *pandas is generous, it does not want us to lose the information by any mistake and needs inplace*

In [ ]:
df.drop('new',axis = 1, inplace = True)
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10 new2  new3
r1    0   1   2   3   4   5   6   7   8    9    A     4
r2   10  11  12  13  14  15  16  17  18   19    A     7
r3   20  21  22  23  24  25  26  27  28   29    A    10
r4   30  31  32  33  34  35  36  37  38   39    A    13
r5   40  41  42  43  44  45  46  47  48   49    A    16
r6   50  51  52  53  54  55  56  57  58   59    A    19
r7   60  61  62  63  64  65  66  67  68   69    A    22
r8   70  71  72  73  74  75  76  77  78   79    A    25
r9   80  81  82  83  84  85  86  87  88   89    A    28
r10  90  91  92  93  94  95  96  97  98   99    A    31

In [ ]:
df.drop(columns='new2', inplace = True)
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  new3
r1    0   1   2   3   4   5   6   7   8    9     4
r2   10  11  12  13  14  15  16  17  18   19     7
r3   20  21  22  23  24  25  26  27  28   29    10
r4   30  31  32  33  34  35  36  37  38   39    13
r5   40  41  42  43  44  45  46  47  48   49    16
r6   50  51  52  53  54  55  56  57  58   59    19
r7   60  61  62  63  64  65  66  67  68   69    22
r8   70  71  72  73  74  75  76  77  78   79    25
r9   80  81  82  83  84  85  86  87  88   89    28
r10  90  91  92  93  94  95  96  97  98   99    31

In [ ]:
df.drop('new3', axis = 1, inplace = True)
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

### Rows
We can retrieve a row by its name or position with **[`loc`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.loc.html)** and **[`iloc`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.iloc.html)**.<br>
**loc** -- Access a group of rows and columns by label(s)

In [ ]:
# df['r1'] # KeyError: 'r1'
df.loc[['r2']] # loc for location in square brackets
# we see that the rows are series as well!

    c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r2  10  11  12  13  14  15  16  17  18   19

Using row's index location with **iloc**, even if our index is labeled.

In [ ]:
df.iloc[[1]] # iloc[index], index based location

    c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r2  10  11  12  13  14  15  16  17  18   19

In [ ]:
# more than one rows -- pass a list of rows!
df.loc[['r1', 'r2', 'r3']]

    c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1   0   1   2   3   4   5   6   7   8    9
r2  10  11  12  13  14  15  16  17  18   19
r3  20  21  22  23  24  25  26  27  28   29

### Grabbing an element or a sub-set of the dataframe

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
df.loc['r1','c1']

0

In [ ]:
df.loc[['r1','r2'],['c1','c2']]

    c1  c2
r1   0   1
r2  10  11

In [ ]:
# another example - random columns and rows in the list
df.loc[['r2','r5'],['c3','c4']]

    c3  c4
r2  12  13
r5  42  43

In [ ]:
df.loc[['r1','r7'],['c4','c4','c8']]

    c4  c4  c8
r1   3   3   7
r7  63  63  67

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
# We can do a conditional selection as well
df > 40

        c1     c2     c3     c4     c5     c6     c7     c8     c9    c10
r1   False  False  False  False  False  False  False  False  False  False
r2   False  False  False  False  False  False  False  False  False  False
r3   False  False  False  False  False  False  False  False  False  False
r4   False  False  False  False  False  False  False  False  False  False
r5   False   True   True   True   True   True   True   True   True   True
r6    True   True   True   True   True   True   True   True   True   True
r7    True   True   True   True   True   True   True   True   True   True
r8    True   True   True   True   True   True   True   True   True   True
r9    True   True   True   True   True   True   True   True   True   True
r10   True   True   True   True   True   True   True   True   True   True

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

This is similar to NumPy boolean mask, lets try this:

    *bool_mask = df % 3 == 0
    *df[bool_mask]
returns values where it is True and NaN where False.

In [ ]:
# Return Divisible by 3
bool_mask = df % 3 == 0
bool_mask
#df[bool_mask]

        c1     c2     c3     c4     c5     c6     c7     c8     c9    c10
r1    True  False  False   True  False  False   True  False  False   True
r2   False  False   True  False  False   True  False  False   True  False
r3   False   True  False  False   True  False  False   True  False  False
r4    True  False  False   True  False  False   True  False  False   True
r5   False  False   True  False  False   True  False  False   True  False
r6   False   True  False  False   True  False  False   True  False  False
r7    True  False  False   True  False  False   True  False  False   True
r8   False  False   True  False  False   True  False  False   True  False
r9   False   True  False  False   True  False  False   True  False  False
r10   True  False  False   True  False  False   True  False  False   True

&#9758; Its not common to use such operation on entire dataframe. We usually use them on a columns or rows instead.<br>
**For example, we don't want a row with NaN values.**<br>
What to do?<br>
Let's have a look at one example.

In [ ]:
# Our original dataframe is
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

Let's apply a condition on column c1, say `c1 > 11`<br>
based on the conditional selection, the out put will be:

In [ ]:
df[df['c1']>11]  # Select * from df where c1 > 11

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
#select c1, c3 from df where c1 > 11
df[df['c1']>11][['c1','c3']]

     c1  c3
r3   20  22
r4   30  32
r5   40  42
r6   50  52
r7   60  62
r8   70  72
r9   80  82
r10  90  92

We don't want `r1` and `r2` as they return NaN or null values. <br>
Let's filter the rows based on condition on column values.

In [ ]:
df[df['c1']>11][['c3','c4','c7']]

     c3  c4  c7
r3   22  23  26
r4   32  33  36
r5   42  43  46
r6   52  53  56
r7   62  63  66
r8   72  73  76
r9   82  83  86
r10  92  93  96

&#9758; The above, **"`df[df['c1']>11]`"** is a dataframe with applied condition, we can select any col from this dataframe.<br> For example:

In [ ]:
result = df[df['c1']>11]
result

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

We can do the above operations, (filtering and selecting a columns) in a single line (stack commonds).

In [ ]:
df[df['c1']>11][['c1', 'c10']]

     c1  c10
r3   20   29
r4   30   39
r5   40   49
r6   50   59
r7   60   69
r8   70   79
r9   80   89
r10  90   99

In [ ]:
# let's grab two columns, we need to pass the list ['c1','c9'] here
df[df['c1']>11][['c1','c9']]  #Select c1, c9 from df where c1 > 11

     c1  c9
r3   20  28
r4   30  38
r5   40  48
r6   50  58
r7   60  68
r8   70  78
r9   80  88
r10  90  98

In [ ]:
# We can do this operation on rows using loc
# Passing multiple rows in a list
df[df['c1']>11].loc[['r3','r4']]

    c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r3  20  21  22  23  24  25  26  27  28   29
r4  30  31  32  33  34  35  36  37  38   39

In [ ]:
result = df[df['c1']==70]
result

    c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r8  70  71  72  73  74  75  76  77  78   79

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
df[df['c1']==70]  #select * from df where Age == 70

    c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r8  70  71  72  73  74  75  76  77  78   79

### Combine 2 conditions
Let's try on c1 for a value > 60 and on c2 for a value > 80

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
df[(df['c1']>60) & (df['c2']>80)]

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

&#9989;**NOTE:**<br>
"and" operator will not work in the above condition and using "and" will return <br>

        *ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

This "ambiguous" means, True, only work for a single booleans at a time "True and False". We need to use "&" instead. ("|" for or)<br>
Try the above code using "and" <br>
The "and" operator gets confused with series of True/False and raise Error

### Let's have a quick look on couple of useful methods.
***We will explore more later on in the course!***

**`reset_index()`** and **`set_index()`**<br>
We can reset the index of our dataframe to numerical index (which is default index), `inplace = True` to make the permanent change. *The existing index will be a new column.*

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
df.reset_index(inplace = True)

In [ ]:
df

  index  c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
0    r1   0   1   2   3   4   5   6   7   8    9
1    r2  10  11  12  13  14  15  16  17  18   19
2    r3  20  21  22  23  24  25  26  27  28   29
3    r4  30  31  32  33  34  35  36  37  38   39
4    r5  40  41  42  43  44  45  46  47  48   49
5    r6  50  51  52  53  54  55  56  57  58   59
6    r7  60  61  62  63  64  65  66  67  68   69
7    r8  70  71  72  73  74  75  76  77  78   79
8    r9  80  81  82  83  84  85  86  87  88   89
9   r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
df.set_index('c2', inplace = True)
df

   index  c1  c3  c4  c5  c6  c7  c8  c9  c10
c2
1     r1   0   2   3   4   5   6   7   8    9
11    r2  10  12  13  14  15  16  17  18   19
21    r3  20  22  23  24  25  26  27  28   29
31    r4  30  32  33  34  35  36  37  38   39
41    r5  40  42  43  44  45  46  47  48   49
51    r6  50  52  53  54  55  56  57  58   59
61    r7  60  62  63  64  65  66  67  68   69
71    r8  70  72  73  74  75  76  77  78   79
81    r9  80  82  83  84  85  86  87  88   89
91   r10  90  92  93  94  95  96  97  98   99

In [ ]:
df

   index  c1  c3  c4  c5  c6  c7  c8  c9  c10
c2
1     r1   0   2   3   4   5   6   7   8    9
11    r2  10  12  13  14  15  16  17  18   19
21    r3  20  22  23  24  25  26  27  28   29
31    r4  30  32  33  34  35  36  37  38   39
41    r5  40  42  43  44  45  46  47  48   49
51    r6  50  52  53  54  55  56  57  58   59
61    r7  60  62  63  64  65  66  67  68   69
71    r8  70  72  73  74  75  76  77  78   79
81    r9  80  82  83  84  85  86  87  88   89
91   r10  90  92  93  94  95  96  97  98   99

** consider, We have a column in our data that could be a useful index,<br>
we want to set that column as an index!**<br>

In [ ]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
columns

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']

In [ ]:
df = pd.DataFrame(data = array_2d, index = rows, columns = columns)
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
abc = 'a b c d e f g h i j'.split() # split at white spaces
# let put newind as a col in the df
df['newind']=abc
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10 newind
r1    0   1   2   3   4   5   6   7   8    9      a
r2   10  11  12  13  14  15  16  17  18   19      b
r3   20  21  22  23  24  25  26  27  28   29      c
r4   30  31  32  33  34  35  36  37  38   39      d
r5   40  41  42  43  44  45  46  47  48   49      e
r6   50  51  52  53  54  55  56  57  58   59      f
r7   60  61  62  63  64  65  66  67  68   69      g
r8   70  71  72  73  74  75  76  77  78   79      h
r9   80  81  82  83  84  85  86  87  88   89      i
r10  90  91  92  93  94  95  96  97  98   99      j

In [ ]:
# setting newind as an index, needs to be inplaced
df.set_index('newind', inplace = True)

In [ ]:
df

        c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
newind
a        0   1   2   3   4   5   6   7   8    9
b       10  11  12  13  14  15  16  17  18   19
c       20  21  22  23  24  25  26  27  28   29
d       30  31  32  33  34  35  36  37  38   39
e       40  41  42  43  44  45  46  47  48   49
f       50  51  52  53  54  55  56  57  58   59
g       60  61  62  63  64  65  66  67  68   69
h       70  71  72  73  74  75  76  77  78   79
i       80  81  82  83  84  85  86  87  88   89
j       90  91  92  93  94  95  96  97  98   99

In [ ]:
df = pd.DataFrame(data=array_2d, index=rows, columns=columns)
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

### `head()`, `tail()`

In [ ]:
# Returns first n rows
df.head() # n = 5 by default

    c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1   0   1   2   3   4   5   6   7   8    9
r2  10  11  12  13  14  15  16  17  18   19
r3  20  21  22  23  24  25  26  27  28   29
r4  30  31  32  33  34  35  36  37  38   39
r5  40  41  42  43  44  45  46  47  48   49

In [ ]:
# Returns last n rows
df.tail(2) # n = 5 by default

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

### `info()`
Provides a concise summary of the DataFrame.

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, r1 to r10
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      10 non-null     int32
 1   c2      10 non-null     int32
 2   c3      10 non-null     int32
 3   c4      10 non-null     int32
 4   c5      10 non-null     int32
 5   c6      10 non-null     int32
 6   c7      10 non-null     int32
 7   c8      10 non-null     int32
 8   c9      10 non-null     int32
 9   c10     10 non-null     int32
dtypes: int32(10)
memory usage: 480.0+ bytes

### `describe()`
Generates descriptive statistics that summarize the central tendency, dispersion and shape of a dataset's distribution, excluding `NaN` values.

In [ ]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [ ]:
df.describe()

,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10
count,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,45.000000,46.000000,47.000000,48.000000,49.000000,50.000000,51.000000,52.000000,53.000000,54.000000
std,30.276504,30.276504,30.276504,30.276504,30.276504,30.276504,30.276504,30.276504,30.276504,30.276504
min,0.000000,1.000000,2.000000,3.000000,4.000000,5.000000,6.000000,7.000000,8.000000,9.000000
25%,22.500000,23.500000,24.500000,25.500000,26.500000,27.500000,28.500000,29.500000,30.500000,31.500000
50%,45.000000,46.000000,47.000000,48.000000,49.000000,50.000000,51.000000,52.000000,53.000000,54.000000
75%,67.500000,68.500000,69.500000,70.500000,71.500000,72.500000,73.500000,74.500000,75.500000,76.500000
max,90.000000,91.000000,92.000000,93.000000,94.000000,95.000000,96.000000,97.000000,98.000000,99.000000

# Excellent!
I want to congratulate here, you are making a great progress, keep it up!

In [ ]:
df2 = pd.read_csv('E:\Breast_Cancer_Diagnostic.csv')

In [ ]:
df2

In [ ]:
df2.info()

In [ ]:
df2.describe(include = 'all')

In [ ]:
df2

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
df2

In [ ]:
df2.describe()