# Useful methods and operations
* unique(), nunique(), value_counts(), sort_values(), apply(), index, column

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data_dic = {'col_1':[1,2,3,4,5],
           'col_2':[111,222,333,111,555],
           'col_3':['alpha','bravo','charlie',np.nan,np.nan],
           }
df = pd.DataFrame(data_dic)
df

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

### <code>unique()</code>
Find and returns all the unique values.<br>
Lets see how it works on all the columns in our dataframe.

In [ ]:
df

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [ ]:
df['col_2'].unique()

array([111, 222, 333, 555], dtype=int64)

In [ ]:
print(df['col_1'].unique())
print(df['col_2'].unique())
print(df['col_3'].unique())
# 111 and NaN are repeated values, unique will only return once.

[1 2 3 4 5]
[111 222 333 555]
['alpha' 'bravo' 'charlie' nan]

### <code>nunique()</code>
Find returns "how many unique values exist".<br>
&#9758; Notice the difference, for NaN, it count a missing value and returns "3" for col_3.

In [ ]:
print(df['col_1'].nunique())
print(df['col_2'].nunique())
print(df['col_3'].nunique())

5
4
3

In [ ]:
df['col_2'].count()   # How many values exist

5

### <code>value_counts()</code>
We want a table with all the values along with no. of times they appeared in our data, value_counts do the work here!<br>
&#9758; for NaN, it count a missing value, nothing in the output.

In [ ]:
df

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [ ]:
df['col_2'].value_counts()

col_2
111    2
222    1
333    1
555    1
Name: count, dtype: int64

In [ ]:
df['col_3'].value_counts()

col_3
alpha      1
bravo      1
charlie    1
Name: count, dtype: int64

In [ ]:
df['col_3'].count()

3

### <code>sort_values()</code>
by default:<br>
* <code>ascending=True
* inplace=False</code>

In [ ]:
df

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [ ]:
df.sort_values(by='col_2') # select * from df order by col_2

   col_1  col_2    col_3
0      1    111    alpha
3      4    111      NaN
1      2    222    bravo
2      3    333  charlie
4      5    555      NaN

In [ ]:
df.sort_values(by='col_2', ascending=False) # select * from df order by col_2

   col_1  col_2    col_3
4      5    555      NaN
2      3    333  charlie
1      2    222    bravo
0      1    111    alpha
3      4    111      NaN

### <code>apply()</code>
Indeed, this is one of the most powerful pandas feature. Using <code>**apply()**</code> method, we can **broadcast** our **customized functions** on our data.<br>
Let's see how to calculate square of col_1

In [ ]:
# Our customized function to calculate the squares
def square(value):
    return value * value

* Let's broadcast our customized function <code>"square"</code> using <code>"apply"</code> method to calculate squares of the col_1 in our DataFrame, df.

In [ ]:
df

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [ ]:
square(3)

9

In [ ]:
df['col_1'].apply(square)

0     1
1     4
2     9
3    16
4    25
Name: col_1, dtype: int64

* The same operation can be conveniently carried out using state of the art <code>**lambda**</code> expression!

In [ ]:
df['col_1'].apply(lambda value : value*value)

0     1
1     4
2     9
3    16
4    25
Name: col_1, dtype: int64

## Good to know

In [ ]:
# Getting index names
df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# Getting column names
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [ ]:
df

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [ ]:
newdf = df.copy()      # Copy
newdf

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [ ]:
aa = df              # Assign
aa

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [ ]:
del newdf['col_1']

In [ ]:
newdf

   col_2    col_3
0    111    alpha
1    222    bravo
2    333  charlie
3    111      NaN
4    555      NaN

In [ ]:
df

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [ ]:
newdf['dd']=2

In [ ]:
newdf

   col_2    col_3  dd
0    111    alpha   2
1    222    bravo   2
2    333  charlie   2
3    111      NaN   2
4    555      NaN   2

In [ ]:
newdf.insert(1, 'new-col2', [1,2,3,4,5])
newdf

   col_2  new-col2    col_3  dd
0    111         1    alpha   2
1    222         2    bravo   2
2    333         3  charlie   2
3    111         4      NaN   2
4    555         5      NaN   2

In [ ]:
newdf['dd'] = newdf['col_2'] * newdf['new-col2']

In [ ]:
newdf['ddd']=11

In [ ]:
newdf

   col_2  new-col2    col_3    dd  ddd
0    111         1    alpha   111   11
1    222         2    bravo   444   11
2    333         3  charlie   999   11
3    111         4      NaN   444   11
4    555         5      NaN  2775   11

# Great Job!
This was little long, but you did it! Let's have a quick over view and move on to use the skills we have learned in the coming exercises!<br>
This was all about pandas that we wanted to learn. <br>
&#9989; Keep practicing to brush-up and add new skills.