In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/Screen Time Data.csv')

In [4]:
df.head()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.drop_duplicates()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0
5,5,04/22/19,Monday,189,68,0,9,3,4,0,0,0
6,6,04/23/19,Tuesday,158,56,18,41,12,15,0,0,0
7,7,04/24/19,Wednesday,135,98,3,33,16,0,0,0,0
8,8,04/25/19,Thursday,52,25,7,3,16,0,0,0,0
9,9,04/26/19,Friday,198,76,8,29,15,0,32,0,0
10,10,04/27/19,Saturday,116,75,10,20,5,0,0,0,0
11,11,04/28/19,Sunday,85,42,22,4,2,0,0,0,0
12,12,04/29/19,Monday,109,46,8,13,9,15,1,0,1
13,13,04/30/19,Tuesday,79,40,2,9,12,0,0,0,1
14,14,05/01/19,Wednesday,127,90,0,10,7,0,0,0,1
15,15,05/02/19,Thursday,170,60,3,2,11,0,0,0,1
16,16,05/03/19,Friday,91,64,2,18,5,1,1,2,1
17,17,05/04/19,Saturday,58,34,4,5,3,0,1,0,1
18,18,05/05/19,Sunday,133,109,5,1,3,0,0,0,1
19,19,05/06/19,Monday,144,81,4,5,3,0,0,0,1
20,20,05/07/19,Tuesday,110,70,5,6,15,0,9,0,1
21,21,05/08/19,Wednesday,122,53,25,26,15,0,0,0,1
22,22,05/09/19,Thursday,96,42,15,16,19,0,0,0,1
23,23,05/10/19,Friday,161,93,13,17,16,1,0,0,1
24,24,05/11/19,Saturday,58,49,1,2,2,0,0,2,1
25,25,05/12/19,Sunday,52,28,1,1,6,0,0,1,1
26,26,05/13/19,Monday,61,37,1,0,4,0,0,0,1
27,27,05/14/19,Tuesday,88,41,2,7,15,0,0,0,1

In [9]:
df1=pd.read_csv('/content/spam_ham_dataset.csv')

In [11]:
df1.head()

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0

In [15]:
df1.duplicated().sum()

np.int64(0)

In [13]:
df2=pd.read_csv('/content/data.csv')

In [14]:
df2.duplicated().sum()

np.int64(1)

In [17]:
df2.drop_duplicates(inplace=True)

In [18]:
df2.duplicated().sum()

np.int64(0)

In [21]:
df['Productivity'].sort_values(ascending=False)

0     22
22    19
8     16
7     16
23    16
20    15
21    15
27    15
9     15
6     12
13    12
15    11
1      9
12     9
14     7
25     6
16     5
10     5
2      4
26     4
19     3
18     3
5      3
4      3
17     3
3      2
11     2
24     2
Name: Productivity, dtype: int64

In [22]:
df.head()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [24]:
df[df['Week Day']=='Friday']

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
9,9,04/26/19,Friday,198,76,8,29,15,0,32,0,0
16,16,05/03/19,Friday,91,64,2,18,5,1,1,2,1
23,23,05/10/19,Friday,161,93,13,17,16,1,0,0,1

In [28]:
df[(df['Week Day']=='Friday') & (df['Total Screen Time ']>100)]

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
9,9,04/26/19,Friday,198,76,8,29,15,0,32,0,0
23,23,05/10/19,Friday,161,93,13,17,16,1,0,0,1

In [ ]:
!pip install ydata_Profiling

In [30]:
from ydata_profiling import ProfileReport

In [31]:
profile=ProfileReport(df,title='Pandas Profiling Report',explorative=True)

In [ ]:
profile

In [34]:
profile.to_file('The Screen time.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [35]:
from google.colab import files
files.download('The Screen time.html')