In [2]:
h="Hello, \nFu*king World"
print(h)

Hello,
Fu*king World

Q1. Create a class Student with attributes: name, roll, and marks.

• Add a method display() to print the student’s details.

• Create two objects and display their information.

In [12]:
class Student:
     def __init__(self, name, roll, dept):
      self.name = name
      self.roll =roll
      self.dept= dept

     def display(self):
      print("Name: ", self.name, "\nRoll: ", self.roll, "\nDepartment: ", self.dept)

In [14]:
S1=Student("Soumitro", "49", "Applied Mathematics")
S1.display()
S2=Student("Tithy", "47", "Food and Nutritional Science")
S2.display()

Name:  Soumitro
Roll:  49
Department:  Applied Mathematics
Name:  Tithy
Roll:  47
Department:  Food and Nutritional Science

Q2. Write a program where:


• Class A has method display1().


• Class B inherits from Class A and adds method display2().

• Class C inherits from Class B and adds method display3().

• Create an object of Class C and call all three methods.

In [19]:
class A:
  def display1(self):
    print("This is in the vast universe")
class B(A):
  def display2(self):
    print("This is in the cosmos")
class C(B):
  def display3(self):
    print("This is the earth")

In [20]:
Earth=C()
Earth.display3()
Earth.display2()
Earth.display1()

This is the earth
This is in the cosmos
This is in the vast universe

Q3. Create a pandas DataFrame from a dictionary containing the following data:

Name Age Marks

Alice 20 85

Bob 22 90

Carol 21 78

David 23 88

Eve 19 65

Display the DataFrame.

In [21]:
import pandas as pd

In [57]:
Sdata = {
   'Name': ['Alice','Bob','Carol','David','Eve'],
   'Age' : [20,22,21,23,19],
   'Marks': [85,90,78,88,65]
 }

In [58]:
St=pd.DataFrame(Sdata)

In [59]:
St

    Name  Age  Marks
0  Alice   20     85
1    Bob   22     90
2  Carol   21     78
3  David   23     88
4    Eve   19     65

In [43]:
St = St.sort_values(by='Marks', ascending=True)

In [45]:
St

    Name Age Marks
4    Eve  19    65
2  Carol  21    78
0  Alice  20    85
3  David  23    88
1    Bob  22    90

Q4. From the DataFrame in Q3:
1. Find all rows where Age > 21.
2. Find names of students who scored Marks ≥ 85.
3. Using pandas, find the Age and Marks of the student named David.

In [61]:
St[St['Age']>21]

    Name  Age  Marks
1    Bob   22     90
3  David   23     88

In [63]:
St[['Name','Marks']][St['Marks']>85]

    Name  Marks
1    Bob     90
3  David     88

In [64]:
St[St['Name'] == 'David']

    Name  Age  Marks
3  David   23     88

Q5. Using the DataFrame in Q3, find:

• The average (mean) marks.

• The maximum marks.

• The minimum marks.

• The minimum age.

In [65]:
St.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [70]:
St['Marks'].mean()

np.float64(81.2)

In [71]:
St['Marks'].max()

90

In [72]:
St['Marks'].min()

65

In [73]:
St['Age'].min()

19