In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Screen Time Data.csv')

In [ ]:
df

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0
5,5,04/22/19,Monday,189,68,0,9,3,4,0,0,0
6,6,04/23/19,Tuesday,158,56,18,41,12,15,0,0,0
7,7,04/24/19,Wednesday,135,98,3,33,16,0,0,0,0
8,8,04/25/19,Thursday,52,25,7,3,16,0,0,0,0
9,9,04/26/19,Friday,198,76,8,29,15,0,32,0,0
10,10,04/27/19,Saturday,116,75,10,20,5,0,0,0,0
11,11,04/28/19,Sunday,85,42,22,4,2,0,0,0,0
12,12,04/29/19,Monday,109,46,8,13,9,15,1,0,1
13,13,04/30/19,Tuesday,79,40,2,9,12,0,0,0,1
14,14,05/01/19,Wednesday,127,90,0,10,7,0,0,0,1
15,15,05/02/19,Thursday,170,60,3,2,11,0,0,0,1
16,16,05/03/19,Friday,91,64,2,18,5,1,1,2,1
17,17,05/04/19,Saturday,58,34,4,5,3,0,1,0,1
18,18,05/05/19,Sunday,133,109,5,1,3,0,0,0,1
19,19,05/06/19,Monday,144,81,4,5,3,0,0,0,1
20,20,05/07/19,Tuesday,110,70,5,6,15,0,9,0,1
21,21,05/08/19,Wednesday,122,53,25,26,15,0,0,0,1
22,22,05/09/19,Thursday,96,42,15,16,19,0,0,0,1
23,23,05/10/19,Friday,161,93,13,17,16,1,0,0,1
24,24,05/11/19,Saturday,58,49,1,2,2,0,0,2,1
25,25,05/12/19,Sunday,52,28,1,1,6,0,0,1,1
26,26,05/13/19,Monday,61,37,1,0,4,0,0,0,1
27,27,05/14/19,Tuesday,88,41,2,7,15,0,0,0,1

In [ ]:
df.shape

(28, 12)

In [ ]:
df.head()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [ ]:
df.head(10)

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0
5,5,04/22/19,Monday,189,68,0,9,3,4,0,0,0
6,6,04/23/19,Tuesday,158,56,18,41,12,15,0,0,0
7,7,04/24/19,Wednesday,135,98,3,33,16,0,0,0,0
8,8,04/25/19,Thursday,52,25,7,3,16,0,0,0,0
9,9,04/26/19,Friday,198,76,8,29,15,0,32,0,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   index                  28 non-null     int64
 1   Date                   28 non-null     object
 2   Week Day               28 non-null     object
 3   Total Screen Time      28 non-null     int64
 4   Social Networking      28 non-null     int64
 5   Reading and Reference  28 non-null     int64
 6   Other                  28 non-null     int64
 7   Productivity           28 non-null     int64
 8   Health and Fitness     28 non-null     int64
 9   Entertainment          28 non-null     int64
 10  Creativity             28 non-null     int64
 11  Yoga                   28 non-null     int64
dtypes: int64(10), object(2)
memory usage: 2.8+ KB

In [ ]:
df.columns

Index(['index', 'Date', 'Week Day', 'Total Screen Time ', 'Social Networking',
       'Reading and Reference', 'Other', 'Productivity', 'Health and Fitness',
       'Entertainment', 'Creativity', 'Yoga'],
      dtype='object')

In [ ]:
df['Creativity']   # pandas series

0     0
1     0
2     0
3     0
4     1
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    2
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    2
25    1
26    0
27    0
Name: Creativity, dtype: int64

In [ ]:
df[['Total Screen Time ']]   # pandas data frame for single column

    Total Screen Time
0                  187
1                  123
2                  112
3                  101
4                   56
5                  189
6                  158
7                  135
8                   52
9                  198
10                 116
11                  85
12                 109
13                  79
14                 127
15                 170
16                  91
17                  58
18                 133
19                 144
20                 110
21                 122
22                  96
23                 161
24                  58
25                  52
26                  61
27                  88

In [ ]:
df[['Creativity','Productivity']]     # pandas data frame for multiple columns

    Creativity  Productivity
0            0            22
1            0             9
2            0             4
3            0             2
4            1             3
5            0             3
6            0            12
7            0            16
8            0            16
9            0            15
10           0             5
11           0             2
12           0             9
13           0            12
14           0             7
15           0            11
16           2             5
17           0             3
18           0             3
19           0             3
20           0            15
21           0            15
22           0            19
23           0            16
24           2             2
25           1             6
26           0             4
27           0            15

In [ ]:
df.columns

Index(['index', 'Date', 'Week Day', 'Total Screen Time ', 'Social Networking',
       'Reading and Reference', 'Other', 'Productivity', 'Health and Fitness',
       'Entertainment', 'Creativity', 'Yoga'],
      dtype='object')

In [ ]:
df.rename(columns={'Total Screen Time ':'Screen Time'})

,index,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0
5,5,04/22/19,Monday,189,68,0,9,3,4,0,0,0
6,6,04/23/19,Tuesday,158,56,18,41,12,15,0,0,0
7,7,04/24/19,Wednesday,135,98,3,33,16,0,0,0,0
8,8,04/25/19,Thursday,52,25,7,3,16,0,0,0,0
9,9,04/26/19,Friday,198,76,8,29,15,0,32,0,0
10,10,04/27/19,Saturday,116,75,10,20,5,0,0,0,0
11,11,04/28/19,Sunday,85,42,22,4,2,0,0,0,0
12,12,04/29/19,Monday,109,46,8,13,9,15,1,0,1
13,13,04/30/19,Tuesday,79,40,2,9,12,0,0,0,1
14,14,05/01/19,Wednesday,127,90,0,10,7,0,0,0,1
15,15,05/02/19,Thursday,170,60,3,2,11,0,0,0,1
16,16,05/03/19,Friday,91,64,2,18,5,1,1,2,1
17,17,05/04/19,Saturday,58,34,4,5,3,0,1,0,1
18,18,05/05/19,Sunday,133,109,5,1,3,0,0,0,1
19,19,05/06/19,Monday,144,81,4,5,3,0,0,0,1
20,20,05/07/19,Tuesday,110,70,5,6,15,0,9,0,1
21,21,05/08/19,Wednesday,122,53,25,26,15,0,0,0,1
22,22,05/09/19,Thursday,96,42,15,16,19,0,0,0,1
23,23,05/10/19,Friday,161,93,13,17,16,1,0,0,1
24,24,05/11/19,Saturday,58,49,1,2,2,0,0,2,1
25,25,05/12/19,Sunday,52,28,1,1,6,0,0,1,1
26,26,05/13/19,Monday,61,37,1,0,4,0,0,0,1
27,27,05/14/19,Tuesday,88,41,2,7,15,0,0,0,1

In [ ]:
df.rename(columns={'Total Screen Time ':'Screen Time'}).head()

,index,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [ ]:
df.head()

,index,Date,Week Day,Total Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [ ]:
# To change permanently use inplace=True
df.rename(columns={'Total Screen Time ':'Screen Time'}, inplace=True)

In [ ]:
df.head()

,index,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [ ]:
df.drop(columns=['Date'])
#df.drop('Date',axis=1)

,index,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,Wednesday,187,89,17,41,22,0,0,0,0
1,1,Thursday,123,78,17,8,9,0,0,0,0
2,2,Friday,112,52,40,8,4,0,3,0,0
3,3,Saturday,101,69,9,38,2,0,3,0,0
4,4,Sunday,56,35,2,43,3,0,1,1,0
5,5,Monday,189,68,0,9,3,4,0,0,0
6,6,Tuesday,158,56,18,41,12,15,0,0,0
7,7,Wednesday,135,98,3,33,16,0,0,0,0
8,8,Thursday,52,25,7,3,16,0,0,0,0
9,9,Friday,198,76,8,29,15,0,32,0,0
10,10,Saturday,116,75,10,20,5,0,0,0,0
11,11,Sunday,85,42,22,4,2,0,0,0,0
12,12,Monday,109,46,8,13,9,15,1,0,1
13,13,Tuesday,79,40,2,9,12,0,0,0,1
14,14,Wednesday,127,90,0,10,7,0,0,0,1
15,15,Thursday,170,60,3,2,11,0,0,0,1
16,16,Friday,91,64,2,18,5,1,1,2,1
17,17,Saturday,58,34,4,5,3,0,1,0,1
18,18,Sunday,133,109,5,1,3,0,0,0,1
19,19,Monday,144,81,4,5,3,0,0,0,1
20,20,Tuesday,110,70,5,6,15,0,9,0,1
21,21,Wednesday,122,53,25,26,15,0,0,0,1
22,22,Thursday,96,42,15,16,19,0,0,0,1
23,23,Friday,161,93,13,17,16,1,0,0,1
24,24,Saturday,58,49,1,2,2,0,0,2,1
25,25,Sunday,52,28,1,1,6,0,0,1,1
26,26,Monday,61,37,1,0,4,0,0,0,1
27,27,Tuesday,88,41,2,7,15,0,0,0,1

In [ ]:
df.drop(columns=['Date','Week Day'])

,index,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,187,89,17,41,22,0,0,0,0
1,1,123,78,17,8,9,0,0,0,0
2,2,112,52,40,8,4,0,3,0,0
3,3,101,69,9,38,2,0,3,0,0
4,4,56,35,2,43,3,0,1,1,0
5,5,189,68,0,9,3,4,0,0,0
6,6,158,56,18,41,12,15,0,0,0
7,7,135,98,3,33,16,0,0,0,0
8,8,52,25,7,3,16,0,0,0,0
9,9,198,76,8,29,15,0,32,0,0
10,10,116,75,10,20,5,0,0,0,0
11,11,85,42,22,4,2,0,0,0,0
12,12,109,46,8,13,9,15,1,0,1
13,13,79,40,2,9,12,0,0,0,1
14,14,127,90,0,10,7,0,0,0,1
15,15,170,60,3,2,11,0,0,0,1
16,16,91,64,2,18,5,1,1,2,1
17,17,58,34,4,5,3,0,1,0,1
18,18,133,109,5,1,3,0,0,0,1
19,19,144,81,4,5,3,0,0,0,1
20,20,110,70,5,6,15,0,9,0,1
21,21,122,53,25,26,15,0,0,0,1
22,22,96,42,15,16,19,0,0,0,1
23,23,161,93,13,17,16,1,0,0,1
24,24,58,49,1,2,2,0,0,2,1
25,25,52,28,1,1,6,0,0,1,1
26,26,61,37,1,0,4,0,0,0,1
27,27,88,41,2,7,15,0,0,0,1

In [ ]:
df.head()

,index,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [ ]:
df.drop(columns=['index'], inplace=True)

In [ ]:
df.head()

,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [ ]:
#Checking null values (if any)
df.isnull()
#df.isna()

,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
#number of null values in each column
df.isnull().sum()

Date                     0
Week Day                 0
Screen Time              0
Social Networking        0
Reading and Reference    0
Other                    0
Productivity             0
Health and Fitness       0
Entertainment            0
Creativity               0
Yoga                     0
dtype: int64

In [ ]:
#Total number of null values in the dataset
df.isna().sum().sum()

np.int64(0)

In [ ]:
# Checking null values in a specific column
df['Creativity'].isna()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
Name: Creativity, dtype: bool

In [ ]:
#number of null values in a specific column
df['Creativity'].isnull().sum()

np.int64(0)

In [ ]:
df['Screen Time'].max()

198

In [ ]:
df['Screen Time'].min()

52

In [ ]:
df['Screen Time'].mean()

np.float64(113.25)

In [ ]:
df['Screen Time'].quantile(0.25)

np.float64(83.5)

In [ ]:
df['Screen Time'].quantile(1)

np.float64(198.0)

In [ ]:
# Descriptive statistics for all numeric columns
df.describe()

,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
count,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000
mean,113.250000,60.714286,8.714286,14.821429,9.071429,1.285714,1.821429,0.214286,0.571429
std,43.562322,22.853571,9.340700,13.754605,6.097532,3.952094,6.188721,0.568112,0.503953
min,52.000000,25.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,83.500000,41.750000,2.000000,4.750000,3.000000,0.000000,0.000000,0.000000,0.000000
50%,111.000000,58.000000,5.000000,9.000000,8.000000,0.000000,0.000000,0.000000,1.000000
75%,137.250000,76.500000,13.500000,21.500000,15.000000,0.000000,1.000000,0.000000,1.000000
max,198.000000,109.000000,40.000000,43.000000,22.000000,15.000000,32.000000,2.000000,1.000000

In [ ]:
df.describe(include='all')

,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
count,28,28,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000,28.000000
unique,28,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,04/17/19,Wednesday,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,113.250000,60.714286,8.714286,14.821429,9.071429,1.285714,1.821429,0.214286,0.571429
std,NaN,NaN,43.562322,22.853571,9.340700,13.754605,6.097532,3.952094,6.188721,0.568112,0.503953
min,NaN,NaN,52.000000,25.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,83.500000,41.750000,2.000000,4.750000,3.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,111.000000,58.000000,5.000000,9.000000,8.000000,0.000000,0.000000,0.000000,1.000000
75%,NaN,NaN,137.250000,76.500000,13.500000,21.500000,15.000000,0.000000,1.000000,0.000000,1.000000
max,NaN,NaN,198.000000,109.000000,40.000000,43.000000,22.000000,15.000000,32.000000,2.000000,1.000000

In [ ]:
df.head()

,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
0,04/17/19,Wednesday,187,89,17,41,22,0,0,0,0
1,04/18/19,Thursday,123,78,17,8,9,0,0,0,0
2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
3,04/20/19,Saturday,101,69,9,38,2,0,3,0,0
4,04/21/19,Sunday,56,35,2,43,3,0,1,1,0

In [ ]:
# Correlation coefficient between Social Networking and Productivity
df['Social Networking'].corr(df['Productivity'])

np.float64(0.12453857477622308)

In [ ]:
# Correlation matrix of every numeric columns or variables
df.corr(numeric_only=True)

,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
Screen Time,1.000000,0.710864,0.185685,0.333433,0.344195,0.201360,0.343897,-0.409306,-0.258123
Social Networking,0.710864,1.000000,0.004461,0.234066,0.124539,-0.092968,0.132916,-0.214764,-0.110716
Reading and Reference,0.185685,0.004461,1.000000,0.204553,0.162942,0.091587,0.012539,-0.302112,-0.381038
Other,0.333433,0.234066,0.204553,1.000000,0.307073,0.236715,0.192795,-0.023360,-0.529736
Productivity,0.344195,0.124539,0.162942,0.307073,1.000000,0.032934,0.186832,-0.336026,-0.001722
Health and Fitness,0.201360,-0.092968,0.091587,0.236715,0.032934,1.000000,-0.075065,-0.094262,-0.066414
Entertainment,0.343897,0.132916,0.012539,0.192795,0.186832,-0.075065,1.000000,-0.083521,-0.203577
Creativity,-0.409306,-0.214764,-0.302112,-0.023360,-0.336026,-0.094262,-0.083521,1.000000,0.203286
Yoga,-0.258123,-0.110716,-0.381038,-0.529736,-0.001722,-0.066414,-0.203577,0.203286,1.000000

In [ ]:
# Correlation matrix of specific columns or variables
df[['Screen Time','Social Networking','Productivity']].corr()

                   Screen Time  Social Networking  Productivity
Screen Time           1.000000           0.710864      0.344195
Social Networking     0.710864           1.000000      0.124539
Productivity          0.344195           0.124539      1.000000

In [ ]:
# Checking duplicate data
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
dtype: bool

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Dropping duplicate data
df.drop_duplicates(inplace=True)
#df.drop_duplicates()

In [ ]:
# Sorting values in ascending order
df['Productivity'].sort_values()

3      2
11     2
24     2
5      3
18     3
19     3
17     3
4      3
2      4
26     4
16     5
10     5
25     6
14     7
12     9
1      9
15    11
6     12
13    12
9     15
21    15
27    15
20    15
7     16
23    16
8     16
22    19
0     22
Name: Productivity, dtype: int64

In [ ]:
# Sorting values in descending order
df['Productivity'].sort_values(ascending=False)

0     22
22    19
8     16
7     16
23    16
20    15
21    15
27    15
9     15
6     12
13    12
15    11
1      9
12     9
14     7
25     6
16     5
10     5
2      4
26     4
19     3
18     3
5      3
4      3
17     3
3      2
11     2
24     2
Name: Productivity, dtype: int64

In [ ]:
#Find and returns all the unique values.
df['Week Day'].unique()

array(['Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday',
       'Tuesday'], dtype=object)

In [ ]:
# Count unique values
df['Week Day'].nunique()

7

In [ ]:
df.nunique()

Date                     28
Week Day                  7
Screen Time              26
Social Networking        27
Reading and Reference    17
Other                    22
Productivity             13
Health and Fitness        4
Entertainment             5
Creativity                3
Yoga                      2
dtype: int64

In [ ]:
# Condition
df[df['Week Day']=='Friday']

,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
9,04/26/19,Friday,198,76,8,29,15,0,32,0,0
16,05/03/19,Friday,91,64,2,18,5,1,1,2,1
23,05/10/19,Friday,161,93,13,17,16,1,0,0,1

In [ ]:
df.columns

Index(['Date', 'Week Day', 'Screen Time', 'Social Networking',
       'Reading and Reference', 'Other', 'Productivity', 'Health and Fitness',
       'Entertainment', 'Creativity', 'Yoga'],
      dtype='object')

In [ ]:
df[['Screen Time', 'Social Networking', 'Productivity']][df['Week Day']=='Friday']

    Screen Time  Social Networking  Productivity
2           112                 52             4
9           198                 76            15
16           91                 64             5
23          161                 93            16

In [ ]:
#Multiple condition
df[(df['Week Day']=='Friday') & (df['Screen Time']>100)]

,Date,Week Day,Screen Time,Social Networking,Reading and Reference,Other,Productivity,Health and Fitness,Entertainment,Creativity,Yoga
2,04/19/19,Friday,112,52,40,8,4,0,3,0,0
9,04/26/19,Friday,198,76,8,29,15,0,32,0,0
23,05/10/19,Friday,161,93,13,17,16,1,0,0,1

In [ ]:
df[(df['Week Day']=='Friday') & (df['Screen Time']>100)][['Screen Time','Productivity']]

    Screen Time  Productivity
2           112             4
9           198            15
23          161            16

In [ ]:
!pip install ydata_Profiling

Collecting ydata_Profiling
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting scipy<1.16,>=1.4.1 (from ydata_Profiling)
  Downloading scipy-1.15.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.1 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (3.10.0)
Requirement already satisfied: pydantic>=2 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (2.11.7)
Requirement already satisfied: PyYAML<6.1,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (6.0.2)
Requirement already satisfied: jinja2<3.2,>=2.11.1 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata_Profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.2,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (2.0.2)
Collecting htmlmin==0.1.12 (from ydata_Profiling)
  Downloading htmlmin-0.1.12.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting phik<0.13,>=0.11.1 (from ydata_Profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.24.0 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.48.2 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata_Profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=3 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (4.4.4)
Collecting imagehash==4.3.1 (from ydata_Profiling)
  Downloading ImageHash-4.3.1-py2.py3-none-any.whl.metadata (8.0 kB)
Requirement already satisfied: wordcloud>=1.9.3 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (1.9.4)
Collecting dacite>=1.8 (from ydata_Profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<=0.61,>=0.56.0 in /usr/local/lib/python3.12/dist-packages (from ydata_Profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.1->ydata_Profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.1->ydata_Profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=2.11.1->ydata_Profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_Profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_Profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_Profiling) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_Profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_Profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_Profiling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_Profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<=0.61,>=0.56.0->ydata_Profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata_Profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.1->ydata_Profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.11.1->ydata_Profiling) (1.5.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->ydata_Profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->ydata_Profiling) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->ydata_Profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2->ydata_Profiling) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.24.0->ydata_Profiling) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.24.0->ydata_Profiling) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.24.0->ydata_Profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.24.0->ydata_Profiling) (2025.8.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata_Profiling) (1.0.1)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_Profiling) (25.3.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_Profiling) (3.5)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_Profiling)
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata_Profiling) (1.17.0)
Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.1/400.1 kB 9.0 MB/s eta 0:00:00
Downloading ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.5/296.5 kB 20.2 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 28.8 MB/s eta 0:00:00
Downloading scipy-1.15.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (37.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 49.7 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 7.7 MB/s eta 0:00:00
Downloading puremagic-1.30-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 3.1 MB/s eta 0:00:00
Building wheels for collected packages: htmlmin
  Building wheel for htmlmin (setup.py) ... done
  Created wheel for htmlmin: filename=htmlmin-0.1.12-py3-none-any.whl size=27081 sha256=e6aff4de0e160c64eb3d840c7301b5c57c2568078400344eb6f6cd9aa526ec1e
  Stored in directory: /root/.cache/pip/wheels/5f/d4/d7/4189b07b5902ee9f3ce0dbb14909fbe8037c39d6c63ffd49c9
Successfully built htmlmin
Installing collected packages: puremagic, htmlmin, scipy, multimethod, dacite, imagehash, visions, phik, ydata_Profiling
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.1
    Uninstalling scipy-1.16.1:
      Successfully uninstalled scipy-1.16.1
Successfully installed dacite-1.9.2 htmlmin-0.1.12 imagehash-4.3.1 multimethod-1.12 phik-0.12.5 puremagic-1.30 scipy-1.15.3 visions-0.8.1 ydata_Profiling-4.16.1

In [ ]:
from ydata_profiling import ProfileReport

In [ ]:
# Creating a profile of the dataset
profile = ProfileReport(df, title='Screen Time Data Analysis', explorative=True)

In [ ]:
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/11 [00:00<?, ?it/s]
 36%|███▋      | 4/11 [00:00<00:00, 38.45it/s]
100%|██████████| 11/11 [00:00<00:00, 48.73it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
#Saving the file as html
profile.to_file('The Screen Time.html')

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
#Downloading the file in PC
from google.colab import files
files.download('The Screen Time.html')