In [1]:
h="Hello, \nFucking World"
print(h)

Hello,
Fucking World

#Bonus Class on Machine Learning
Information is organised and data is raw...

ML is macine is learnig from info we give


1.   Supervised
2.   Unsupervised
3.   Reinforcement learning (mostly used for robotics)

to do the data science we need to learn 1 and 2 mostly

#Supervised
:Output(Label Data) is already inside the dataset and given to the model
eg. y=mx+c; here for each x if y is given then this (simple linear regression) equation is for supervised.... (here m is know as gradient)

So, we need

1.   Regression: If our input and output, both is always countinuous/ numerical

        *   Simple Linear Regression
        *   Polynomial Regression


2.   Classification: If our output is always catagorical  (This or That)


        *   Logistic Regression: Take input continuous and/or catagorical but  output is catagorical.  (Heart Disease)
        *   SVM
        *   KNN
        *   Descision Tree
        *   Random Forest
        *   Naive Bayes (Text releated)
              *  Gousian
              *  Multinomial
              *  Bernoli

            They are builtin in skitlearn



#Unsupervised



1.   K-means
2.   PCA (When Feachers are more then 500/1000 we need to dimensionally reduce it... so use principle component analysis)

In [1]:
import pandas as pd
import sklearn as sl

Feacher encoding techniqe are there to train it: level encoding technique

Data science is a statistical ai

when connected with generec ai it creates the ai

gpt:generic pretend transformer

#Machine Learning Steps

1.   Load Datasets
2.   Pre processing (Cleaning, engineering, feature scaling, encoading)
3.   Separate data in x and y (dependent and independent)
4.   Split Dataset (Train 80% and test 20%): use sklearn's spliting api ([Scikitlearn](https://scikit-learn.org/stable/api/index.html): is a ml library (NLP: is needed for jobs))
5.   Model Training
6.   Model Testing/Validation

#We will use a dataset of NAS to just fit it

In [18]:
import pandas as pd
df=pd.read_csv('/content/nasdaq100.csv', sep=';')

In [20]:
df1=df.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            12 non-null     object
 1   Starting (USD)  12 non-null     int64
 2   Ending (USD)    12 non-null     int64
dtypes: int64(2), object(1)
memory usage: 420.0+ bytes

In [9]:
df.head()

       Date  Starting (USD)  Ending (USD)
0  01.01.24           16800         16500
1  01.12.23           15900         16100
2  01.11.23           15800         15300
3  01.10.23           16100         16200
4  01.09.23           16300         15700

In [13]:
df.shape

(12, 3)

In [21]:
df.drop(df[['Date']], axis=1, inplace=True) #just a double sq bracker will convert the data series into dataframe

In [22]:
df

    Starting (USD)  Ending (USD)
0            16800         16500
1            15900         16100
2            15800         15300
3            16100         16200
4            16300         15700
5            16800         16400
6            15900         16200
7            15800         15500
8            16150         16100
9            16300         15800
10           16200         16200
11           16300         15700

y=output=label
X=input=feature (in sklearn docuumentation the xis in capital so to reduce problem we take x as X)

In [23]:
df.columns

Index(['Starting (USD)', 'Ending (USD)'], dtype='object')

In [37]:
X=df[['Starting (USD)']]
y=df[['Ending (USD)']]

In [38]:
X.head()

   Starting (USD)
0           16800
1           15900
2           15800
3           16100
4           16300

In [39]:
y.head()

   Ending (USD)
0         16500
1         16100
2         15300
3         16200
4         15700

In [27]:
from sklearn.model_selection import train_test_split

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [41]:
X.shape

(12, 1)

In [42]:
X_train.shape

(9, 1)

In [43]:
X_train

    Starting (USD)
8            16150
5            16800
2            15800
1            15900
11           16300
4            16300
7            15800
3            16100
6            15900

In [31]:
from sklearn.linear_model import LinearRegression

In [33]:
model=LinearRegression()

In [44]:
model.fit(X,y)

LinearRegression()

In [45]:
model.fit(X_train, y_train)

LinearRegression()

In [46]:
model.score(X,y)

0.35022802756039384

To have good model 70+ is ok

90+ is good

99 is best

100 might be over fed

In [47]:
model.score(X_train, y_train)

0.24859659077190366

In [49]:
model.predict([[16800]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[16304.91967871]])